In [3]:
import duckdb
con = duckdb.connect('../data/olist.db')

def q(sql):
    return con.execute(sql).df()

day 1

In [4]:
q("""
select * from orders
""")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [5]:
q("""
select 
  order_id, order_status, order_purchase_timestamp 
from orders 
where order_status = 'delivered'
""")

                               order_id order_status order_purchase_timestamp
0      e481f51cbdc54678b7cc49136f2d6af7    delivered      2017-10-02 10:56:33
1      53cdb2fc8bc7dce0b6741e2150273451    delivered      2018-07-24 20:41:37
2      47770eb9100c2d0c44946d9cf07ec65d    delivered      2018-08-08 08:38:49
3      949d5b44dbf5de918fe9c16f97b45f8a    delivered      2017-11-18 19:28:06
4      ad21c59c0840e6cb83a9ceb5573f8159    delivered      2018-02-13 21:18:39
...                                 ...          ...                      ...
96473  9c5dedf39a927c1b2549525ed64a053c    delivered      2017-03-09 09:54:05
96474  63943bddc261676b46f01ca7ac2f7bd8    delivered      2018-02-06 12:58:58
96475  83c1379a015df1e13d02aae0204711ab    delivered      2017-08-27 14:46:43
96476  11c177c8e97725db2631073c19f07b62    delivered      2018-01-08 21:28:27
96477  66dea50a8b16d9b4dee7af250b4be1a5    delivered      2018-03-08 20:57:30

[96478 rows x 3 columns]

In [6]:
q("""
select distinct
  order_status
from orders 
""")

  order_status
0  unavailable
1      shipped
2    delivered
3     canceled
4      created
5     invoiced
6   processing
7     approved

In [7]:
q("""
select
  order_id, order_status, order_purchase_timestamp
from orders
where order_status != 'delivered';
""")

                              order_id order_status order_purchase_timestamp
0     136cce7faa42fdb2cefd53fdc79a6098     invoiced      2017-04-11 12:22:08
1     ee64d42b8cf066f35eac1cf57de1aa85      shipped      2018-06-04 16:44:48
2     0760a852e4e9d89eb77bf631eaaf1c84     invoiced      2018-08-03 17:44:42
3     15bed8e2fec7fdbadb186b57c46c92f2   processing      2017-09-03 14:22:03
4     6942b8da583c2f9957e990d028607019      shipped      2018-01-10 11:33:07
...                                ...          ...                      ...
2958  3a3cddda5a7c27851bd96c3313412840     canceled      2018-08-31 16:13:44
2959  e9e64a17afa9653aacf2616d94c005b8   processing      2018-01-05 23:07:24
2960  a89abace0dcc01eeb267a9660b5ac126     canceled      2018-09-06 18:45:47
2961  a69ba794cc7deb415c3e15a0a3877e69  unavailable      2017-08-23 16:28:04
2962  5fabc81b6322c8443648e1b21a6fef21  unavailable      2017-10-10 10:50:03

[2963 rows x 3 columns]

In [8]:
q("""
select
  order_status,
  count(*) as count  
from orders
group by order_status
""")

  order_status  count
0     approved      2
1     canceled    625
2  unavailable    609
3     invoiced    314
4   processing    301
5      created      5
6    delivered  96478
7      shipped   1107

In [9]:
q("""
select
  order_status,
  count(*) as count  
from orders
group by order_status
order by count DESC
""")

  order_status  count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

In [10]:
q("""
select
  year(order_purchase_timestamp) as order_year,
  count(*) as count
from orders
where order_status = 'delivered'
group by 
  order_year
order by count DESC
""")

   order_year  count
0        2018  52783
1        2017  43428
2        2016    267

In [11]:
q("""
select
  order_status,
  count(*) as count
from orders
group by order_status
having count > 1000
""")

  order_status  count
0    delivered  96478
1      shipped   1107

home work for day 2

In [12]:
q("""
select
  customer_state,
  count(distinct customer_unique_id) as unique_customers
from orders
join customers on orders.customer_id = customers.customer_id
group by customer_state
order by unique_customers DESC
limit 10
""")

  customer_state  unique_customers
0             SP             40302
1             RJ             12384
2             MG             11259
3             RS              5277
4             PR              4882
5             SC              3534
6             BA              3277
7             DF              2075
8             ES              1964
9             GO              1952

In [13]:
q("""
select
  payment_type,
  avg(payment_value) as payment_avg
from order_payments
group by payment_type
""")

  payment_type  payment_avg
0      voucher    65.703354
1   debit_card   142.570170
2  not_defined     0.000000
3       boleto   145.034435
4  credit_card   163.319021

In [14]:
q("""
select
  seller_id,
  count(*) as order_count
from order_items
group by seller_id
order by order_count DESC
limit 5
""")

                          seller_id  order_count
0  6560211a19b47992c3666cc44a7e94c0         2033
1  4a3ca9315b744ce9f8e9374361493884         1987
2  1f50f920176fa81dab994f9023523100         1931
3  cc419e0650a3c5ba77189a1882b7556a         1775
4  da8622b14eb17ae2831f4ac5b9dab84a         1551

day 2

In [15]:
q("""
SELECT COUNT(*) 
FROM orders
INNER JOIN customers ON orders.customer_id = customers.customer_id
""")

   count_star()
0         99441

In [16]:
q("""
SELECT COUNT(*)
FROM orders
LEFT JOIN customers ON orders.customer_id = customers.customer_id
""")

   count_star()
0         99441

In [17]:
q("""
SELECT COUNT(*)
FROM orders
INNER JOIN order_reviews ON orders.order_id = order_reviews.order_id
""")

   count_star()
0         99224

In [18]:
q("""
SELECT COUNT(*)
FROM orders
LEFT JOIN order_reviews ON orders.order_id = order_reviews.order_id
""")

   count_star()
0         99992

In [19]:
q("""
select
  orders.order_id,
  orders.order_status,
  order_reviews.review_score
from orders
left join order_reviews on orders.order_id = order_reviews.order_id
where order_status = 'delivered'
""")

                               order_id order_status  review_score
0      73fc7af87114b39712e6da79b0a377eb    delivered             4
1      a548910a1c6147796b98fdf73dbeba33    delivered             5
2      f9e4b658b201a9f2ecdecbb34bed034b    delivered             5
3      658677c97b385a9be170737859d3511b    delivered             5
4      8e6bfb81e283fa7e4f11123a3fb894f1    delivered             5
...                                 ...          ...           ...
97002  e8ede6a466c4c9bb0a9db9a3d87f7a63    delivered          <NA>
97003  3deeaa4d253d9612fe55428163839325    delivered          <NA>
97004  e8606bd877aee06d98501a6436ee8576    delivered          <NA>
97005  ce6c67f20356e5d9c8e6fa1d8f7becea    delivered          <NA>
97006  9757bb9b0d295ca539b1b15c3eab9b2e    delivered          <NA>

[97007 rows x 3 columns]

In [20]:
q("""
select
  customers.customer_unique_id,
  orders.order_id,
  order_reviews.review_score,
  orders.order_status
from customers
left join orders on customers.customer_id = orders.customer_id
left join order_reviews on orders.order_id = order_reviews.order_id
where order_status = 'delivered'
""")

,customer_unique_id,order_id,review_score,order_status
0,68a5590b9926689be4e10f4ae2db21a8,73fc7af87114b39712e6da79b0a377eb,4,delivered
1,64190b91b656ab8f37eb89b93dc84584,a548910a1c6147796b98fdf73dbeba33,5,delivered
2,1d47144362c14e94ccdd213e8ec277d5,f9e4b658b201a9f2ecdecbb34bed034b,5,delivered
3,c8cf6cb6b838dc7a33ed199b825e8616,658677c97b385a9be170737859d3511b,5,delivered
4,d16000272660a1fef81482ad75ba572a,8e6bfb81e283fa7e4f11123a3fb894f1,5,delivered
...,...,...,...,...
97002,68b989ae809071cc660c7ac6beabf867,a785f992778e63bfb3b2288b684217a2,<NA>,delivered
97003,f6f380d65a3df4a73ca15cd8ecc08d2e,9757bb9b0d295ca539b1b15c3eab9b2e,<NA>,delivered
97004,a1c537c2f5231abb4729ee7c83c4bbba,4ac05edf248d6206469e17c32e52c9ac,<NA>,delivered
97005,367f4686d7112d69feed92b02a1775ed,d731191f76c39fe5c7d22edddb6836ba,<NA>,delivered
97006,753fd2847cd950be551bee66c494d8f1,cc0c2816e800ee2d10ad0d51f37ab289,<NA>,delivered

In [21]:
q("""
select
  customers.customer_state,
  avg(order_reviews.review_score) as avg_review_score
from customers
left join orders on customers.customer_id = orders.customer_id
left join order_reviews on orders.order_id = order_reviews.order_id
where orders.order_status = 'delivered'
group by customer_state
order by avg_review_score DESC
""")

   customer_state  avg_review_score
0              SP          4.246196
1              AP          4.242424
2              PR          4.238260
3              AM          4.220690
4              MG          4.192707
5              RS          4.185496
6              MS          4.169014
7              RO          4.165289
8              TO          4.153846
9              RN          4.150106
10             MT          4.147392
11             DF          4.131642
12             SC          4.131050
13             GO          4.102904
14             AC          4.087500
15             PE          4.085535
16             ES          4.082406
17             PB          4.077973
18             PI          3.995763
19             RJ          3.963439
20             CE          3.938088
21             BA          3.929452
22             PA          3.912673
23             SE          3.907186
24             RR          3.902439
25             AL          3.841709
26             MA          3.839385

In [22]:
q("""
select
    customers.customer_state,
    sum(order_items.price + order_items.freight_value) as revenue,
    count(*) as no_orders
from customers
left join orders on customers.customer_id = orders.customer_id
left join order_items on orders.order_id = order_items.order_id
where orders.order_status = 'delivered'
group by customer_state
order by no_orders DESC
""")

   customer_state     revenue  no_orders
0              SP  5769703.15      46448
1              RJ  2055401.57      14143
2              MG  1818891.67      12916
3              RS   861472.79       6134
4              PR   781708.80       5649
5              SC   595127.78       4097
6              BA   591137.81       3683
7              DF   346123.35       2355
8              GO   334212.35       2277
9              ES   317657.93       2225
10             PE   308972.05       1746
11             CE   266436.77       1426
12             PA   212023.57       1054
13             MT   181224.42       1037
14             MS   134367.55        811
15             MA   147803.55        800
16             PB   137838.55        586
17             PI   105178.19        523
18             RN   100714.78        521
19             AL    94172.49        427
20             SE    70289.13        375
21             TO    60007.37        310
22             RO    56966.00        273
23             AM    27585.47        163
24             AC    19575.33         91
25             AP    16141.81         81
26             RR     9039.52         46

In [23]:
q("""
select
    customers.customer_state,
    sum(order_items.price + order_items.freight_value) as revenue,
    avg(order_reviews.review_score) as avg_review_score,
    count(*) as no_orders
from customers
left join orders on customers.customer_id = orders.customer_id
left join order_items on orders.order_id = order_items.order_id
left join order_reviews on orders.order_id = order_reviews.order_id
where orders.order_status = 'delivered'
group by customer_state
order by revenue DESC
""")

   customer_state     revenue  avg_review_score  no_orders
0              SP  5799283.95          4.177227      46714
1              RJ  2063593.64          3.871611      14224
2              MG  1826486.53          4.122123      12995
3              RS   865877.26          4.092325       6182
4              PR   785095.06          4.144476       5673
5              SC   597067.83          4.045856       4112
6              BA   593408.37          3.860725       3703
7              DF   348601.41          4.056261       2381
8              GO   337665.51          4.038462       2297
9              ES   318466.51          4.017234       2236
10             PE   310257.50          4.022989       1758
11             CE   267267.58          3.867275       1431
12             PA   212658.82          3.842459       1061
13             MT   181579.03          4.008746       1040
14             MA   148141.69          3.765957        805
15             PB   137953.28          4.039587        587
16             MS   136005.96          4.073082        823
17             PI   105259.41          3.961464        524
18             RN   100833.26          4.113462        523
19             AL    94475.18          3.815421        431
20             SE    70289.13          3.898123        375
21             TO    60007.37          4.155340        310
22             RO    56966.00          4.073529        273
23             AM    27668.61          4.092025        164
24             AC    19575.33          4.131868         91
25             AP    16141.81          4.262500         81
26             RR     9039.52          3.891304         46

homework day 2

In [24]:
q("""
select 
  sellers.seller_id,  
  sum(order_items.price + order_items.freight_value) as revenue
from order_items
left join sellers on sellers.seller_id = order_items.seller_id
group by sellers.seller_id
order by revenue DESC
limit 10
""")

                          seller_id    revenue
0  4869f7a5dfa277a7dca6462dcf3b52b2  249640.70
1  7c67e1448b00f6e969d365cea6b010ab  239536.44
2  53243585a1d6dc2643021fd1853d8905  235856.68
3  4a3ca9315b744ce9f8e9374361493884  235539.96
4  fa1c13f2614d7b5c4749cbc52fecda94  204084.73
5  da8622b14eb17ae2831f4ac5b9dab84a  185192.32
6  7e93a43ef30c4f03f38b393420bc753a  182754.05
7  1025f0e2d44d7041d6cf58b6550e0bfa  172860.69
8  7a67c85e85bb2ce8582c35f2203ad736  162648.38
9  955fee9216a65b617aa5c0531780ce60  160602.68

In [25]:
q("""
select
    avg(no_orders)
from (
    select
    order_items.order_id,
    count(order_item_id) as no_orders
    from order_items
    group by order_id) as asghar
""")

   avg(no_orders)
0        1.141731

In [26]:
q("""
select
  category_translation.product_category_name_english,
  avg(order_reviews.review_score) as avg_review_score
from order_items
left join order_reviews on order_items.order_id = order_reviews.order_id
left join products on order_items.product_id = products.product_id
left join category_translation on products.product_category_name = category_translation.product_category_name
group by product_category_name_english
order by avg_review_score DESC
""")

   product_category_name_english  avg_review_score
0              cds_dvds_musicals          4.642857
1      fashion_childrens_clothes          4.500000
2         books_general_interest          4.446266
3        costruction_tools_tools          4.444444
4                        flowers          4.419355
..                           ...               ...
67         fashion_male_clothing          3.641221
68                home_comfort_2          3.629630
69              office_furniture          3.493183
70           diapers_and_hygiene          3.256410
71         security_and_services          2.500000

[72 rows x 2 columns]

day 3

In [27]:
q("""
with order_items_counts as (
  select
  order_items.order_id,
  count(order_item_id) as no_orders
  from order_items
  group by order_id
  )
select avg(no_orders)
from order_items_counts
""")

   avg(no_orders)
0        1.141731

In [28]:
q("""
with revenue_per_order as (
    select 
    order_items.order_id,
    customers.customer_id,
    customers.customer_state,
    order_items.price + order_items.freight_value as revenue
    from order_items
    left join orders on order_items.order_id = orders.order_id
    left join customers on orders.customer_id = customers.customer_id
)
select
    customer_state,
    avg(revenue)
from revenue_per_order
group by customer_state
""")

   customer_state  avg(revenue)
0              PI    199.506052
1              RR    193.550385
2              MS    166.003260
3              AP    198.326829
4              TO    194.775937
5              SE    189.694338
6              GO    149.038547
7              ES    143.972478
8              AM    168.701394
9              PR    139.535791
10             SC    146.123946
11             MT    176.463469
12             AL    216.732883
13             RJ    146.078742
14             BA    160.965167
15             RS    142.073257
16             CE    186.472463
17             RN    192.618299
18             AC    213.801087
19             PA    201.525102
20             SP    124.800905
21             MG    141.378741
22             MA    183.461153
23             DF    146.811904
24             PE    178.426185
25             RO    207.043237
26             PB    234.199020

In [29]:
q("""
with revenue_per_order as (
    select 
    order_items.order_id,
    customers.customer_id,
    customers.customer_state,
    order_items.price + order_items.freight_value as revenue
    from order_items
    left join orders on order_items.order_id = orders.order_id
    left join customers on orders.customer_id = customers.customer_id
),
    avg_rev_per_ord_per_st as (
    select
        customer_state,
        avg(revenue) as avg_revenue
    from revenue_per_order
    group by customer_state
),
  
    avg_over_all_state as (
  select
    avg(avg_revenue) as overall_avg
  from avg_rev_per_ord_per_st
)

select
  *
from avg_rev_per_ord_per_st
cross join avg_over_all_state
where avg_rev_per_ord_per_st.avg_revenue > avg_over_all_state.overall_avg
""")

   customer_state  avg_revenue  overall_avg
0              CE   186.472463   175.632614
1              RN   192.618299   175.632614
2              AC   213.801087   175.632614
3              PA   201.525102   175.632614
4              MT   176.463469   175.632614
5              AL   216.732883   175.632614
6              SE   189.694338   175.632614
7              PE   178.426185   175.632614
8              RO   207.043237   175.632614
9              PB   234.199020   175.632614
10             AP   198.326829   175.632614
11             TO   194.775937   175.632614
12             PI   199.506052   175.632614
13             RR   193.550385   175.632614
14             MA   183.461153   175.632614

In [30]:
q("""
with cte1 as (
    select
    customers.customer_unique_id,
    orders.order_purchase_timestamp,
    row_number() over(
        partition by customer_unique_id
        order by order_purchase_timestamp
    ) as order_rank,
    lag(order_purchase_timestamp) over(
        partition by customer_unique_id
        order by order_purchase_timestamp
    ) as previous_order_date
    from orders
    left join customers on customers.customer_id = orders.customer_id
  ),

    cte2 as (
    select
        *,
        datediff('day', previous_order_date, order_purchase_timestamp) as days_between
    from cte1
    where order_rank > 1
  )

select median(days_between) from cte2
""")

   median(days_between)
0                  28.0

day 4

In [31]:
q("""
WITH customer_stats AS (
    SELECT
        customers.customer_unique_id,
        SUM(order_items.price + order_items.freight_value) AS revenue,
        COUNT(DISTINCT orders.order_id) AS no_orders,
        AVG(order_reviews.review_score) AS avg_review_score
    FROM customers
    LEFT JOIN orders ON customers.customer_id = orders.customer_id
    LEFT JOIN order_items ON orders.order_id = order_items.order_id
    LEFT JOIN order_reviews ON orders.order_id = order_reviews.order_id
    WHERE orders.order_status = 'delivered'
    GROUP BY customers.customer_unique_id
)

SELECT *
FROM customer_stats
ORDER BY revenue DESC
LIMIT 10
""")

                 customer_unique_id   revenue  no_orders  avg_review_score
0  0a0a92112bd4c708ca5fde585afaa872  13664.08          1               1.0
1  da122df9eeddfedc1dc1f5349a1a690c   7571.63          2               5.0
2  763c8b1c9c68a0229c42c9fc6f662b93   7274.88          1               1.0
3  dc4802a71eae9be1dd28f5d788ceb526   6929.31          1               5.0
4  459bef486812aa25204be022145caa62   6922.21          1               NaN
5  ff4159b92c40ebe40454e3e6a7c35ed6   6726.66          1               5.0
6  4007669dec559734d6f53e029e360987   6081.54          1               1.0
7  eebb5dda148d3893cdaf5b5ca3040ccb   4764.34          1               4.0
8  48e1ac109decbb87765a3eade6854098   4681.78          1               5.0
9  c8460e4251689ba205045f3ea17884a1   4655.88          4               4.0

In [ ]:
q = ("""
WITH customer_order_years AS ( 
	SELECT 
		customers.customer_unique_id,
		MIN(order_purchase_timestamp) as first_order_date,
		MAX(order_purchase_timestamp) as last_order_date,
		COUNT(DISTINCT orders.order_id) as total_orders
	FROM customers
	LEFT JOIN orders ON customers.customer_id = orders.customer_id
	WHERE orders.order_status = 'delivered'
	GROUP BY customers.customer_unique_id
	HAVING total_orders > 1
)

SELECT
	*
FROM customer_order_years
WHERE YEAR(first_order_date) = 2017 AND YEAR(last_order_date) = 2018
""")

In [ ]:
q = ("""
WITH
  customer_orders AS (
    SELECT
      customers.customer_unique_id,
      order_purchase_timestamp,
      MIN(order_purchase_timestamp) OVER (
        PARTITION BY
          customers.customer_unique_id
      ) AS first_ever_order_date
    FROM
      customers
      LEFT JOIN orders ON orders.customer_id = customers.customer_id
  ),
  customer_return AS (
    SELECT
      *,
      CASE
        WHEN order_purchase_timestamp = first_ever_order_date THEN 'new'
        ELSE 'returning'
      END AS customer_situation
    FROM
      customer_orders
    WHERE
      YEAR (order_purchase_timestamp) = 2018
  )
SELECT
  SUM(
    CASE
      WHEN customer_situation = 'new' THEN 1
      ELSE 0
    END
  ) AS no_new,
  SUM(
    CASE
      WHEN customer_situation = 'returning' THEN 1
      ELSE 0
    END
  ) AS no_returning,
  MONTH (order_purchase_timestamp) AS month_order
FROM
  customer_return
GROUP BY
  month_order
""")