In [1]:
import duckdb
con = duckdb.connect('../data/olist.db')

def q(sql):
    return con.execute(sql).df()

day 1

In [20]:
q("""
select * from orders
""")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [11]:
q("""
select 
  order_id, order_status, order_purchase_timestamp 
from orders 
where order_status = 'delivered'
""")

                               order_id order_status order_purchase_timestamp
0      e481f51cbdc54678b7cc49136f2d6af7    delivered      2017-10-02 10:56:33
1      53cdb2fc8bc7dce0b6741e2150273451    delivered      2018-07-24 20:41:37
2      47770eb9100c2d0c44946d9cf07ec65d    delivered      2018-08-08 08:38:49
3      949d5b44dbf5de918fe9c16f97b45f8a    delivered      2017-11-18 19:28:06
4      ad21c59c0840e6cb83a9ceb5573f8159    delivered      2018-02-13 21:18:39
...                                 ...          ...                      ...
96473  9c5dedf39a927c1b2549525ed64a053c    delivered      2017-03-09 09:54:05
96474  63943bddc261676b46f01ca7ac2f7bd8    delivered      2018-02-06 12:58:58
96475  83c1379a015df1e13d02aae0204711ab    delivered      2017-08-27 14:46:43
96476  11c177c8e97725db2631073c19f07b62    delivered      2018-01-08 21:28:27
96477  66dea50a8b16d9b4dee7af250b4be1a5    delivered      2018-03-08 20:57:30

[96478 rows x 3 columns]

In [16]:
q("""
select distinct
  order_status
from orders 
""")

  order_status
0      created
1      shipped
2     canceled
3     approved
4    delivered
5  unavailable
6     invoiced
7   processing

In [18]:
q("""
select
  order_id, order_status, order_purchase_timestamp
from orders
where order_status != 'delivered';
""")

                              order_id order_status order_purchase_timestamp
0     136cce7faa42fdb2cefd53fdc79a6098     invoiced      2017-04-11 12:22:08
1     ee64d42b8cf066f35eac1cf57de1aa85      shipped      2018-06-04 16:44:48
2     0760a852e4e9d89eb77bf631eaaf1c84     invoiced      2018-08-03 17:44:42
3     15bed8e2fec7fdbadb186b57c46c92f2   processing      2017-09-03 14:22:03
4     6942b8da583c2f9957e990d028607019      shipped      2018-01-10 11:33:07
...                                ...          ...                      ...
2958  3a3cddda5a7c27851bd96c3313412840     canceled      2018-08-31 16:13:44
2959  e9e64a17afa9653aacf2616d94c005b8   processing      2018-01-05 23:07:24
2960  a89abace0dcc01eeb267a9660b5ac126     canceled      2018-09-06 18:45:47
2961  a69ba794cc7deb415c3e15a0a3877e69  unavailable      2017-08-23 16:28:04
2962  5fabc81b6322c8443648e1b21a6fef21  unavailable      2017-10-10 10:50:03

[2963 rows x 3 columns]

In [19]:
q("""
select
  order_status,
  count(*) as count  
from orders
group by order_status
""")

  order_status  count
0     canceled    625
1      shipped   1107
2     approved      2
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7    delivered  96478

In [23]:
q("""
select
  order_status,
  count(*) as count  
from orders
group by order_status
order by count DESC
""")

  order_status  count
0    delivered  96478
1      shipped   1107
2     canceled    625
3  unavailable    609
4     invoiced    314
5   processing    301
6      created      5
7     approved      2

In [30]:
q("""
select
  year(order_purchase_timestamp) as order_year,
  count(*) as count
from orders
where order_status = 'delivered'
group by 
  order_year
order by count DESC
""")

   order_year  count
0        2018  52783
1        2017  43428
2        2016    267

In [36]:
q("""
select
  order_status,
  count(*) as count
from orders
group by order_status
having count > 1000
""")

  order_status  count
0    delivered  96478
1      shipped   1107

home work for day 2

In [74]:
q("""
select
  customer_state,
  count(distinct customer_unique_id) as unique_customers
from orders
join customers on orders.customer_id = customers.customer_id
group by customer_state
order by unique_customers DESC
limit 10
""")

  customer_state  unique_customers
0             SP             40302
1             RJ             12384
2             MG             11259
3             RS              5277
4             PR              4882
5             SC              3534
6             BA              3277
7             DF              2075
8             ES              1964
9             GO              1952

In [68]:
q("""
select
  payment_type,
  avg(payment_value) as payment_avg
from order_payments
group by payment_type
""")

  payment_type  payment_avg
0       boleto   145.034435
1  credit_card   163.319021
2      voucher    65.703354
3   debit_card   142.570170
4  not_defined     0.000000

In [65]:
q("""
select
  seller_id,
  count(*) as order_count
from order_items
group by seller_id
order by order_count DESC
limit 5
""")

                          seller_id  order_count
0  6560211a19b47992c3666cc44a7e94c0         2033
1  4a3ca9315b744ce9f8e9374361493884         1987
2  1f50f920176fa81dab994f9023523100         1931
3  cc419e0650a3c5ba77189a1882b7556a         1775
4  da8622b14eb17ae2831f4ac5b9dab84a         1551